import type { ResumeData } from "./types"

export async function getResumeData(): Promise<ResumeData> {
  return {
    name: "Nishant Kalane",
    title: "AI/ML Researcher & Full Stack Developer",
    tagline: "Building intelligent systems & presenting them with clarity.",
    contact: {
      email: "nishantnkalane@gmail.com",
      phone: "+91 9175646405",
      location: "Nagpur, Maharashtra, India",
      github: "https://github.com/nishantkalane",
      linkedin: "https://linkedin.com/in/nishantkalane",
      profile: "https://drive.google.com/file/d/1Xm94y-QPgPBaw-hQum-_00tkqu4XU_Qt/view?usp=drive_link",
    },
    projects: [
      {
        name: "Kanthaka",
        description:
          "RF-enabled healthcare robotics project focused on improving patient care through intelligent automation and remote monitoring capabilities.",
        technologies: ["Python", "RF Communication", "Robotics", "Healthcare IoT", "Machine Learning"],
        features: [
          "RF-enabled remote patient monitoring",
          "Intelligent healthcare automation",
          "Real-time data collection and analysis",
          "Integration with existing healthcare systems",
        ],
        github: "https://github.com/nishantkalane/kanthaka",
        demo: "https://kanthaka-demo.vercel.app",
      },
      {
        name: "Sentiment Sense",
        description:
          "Advanced NLP tool for sentiment analysis and sarcasm detection with comprehensive data visualization capabilities for social media and text analysis.",
        technologies: ["Python", "NLP", "Machine Learning", "Data Visualization", "Sentiment Analysis"],
        features: [
          "Multi-class sentiment analysis",
          "Sarcasm detection algorithms",
          "Interactive data visualization dashboard",
          "Real-time text processing",
          "Export capabilities for analysis results",
        ],
        github: "https://github.com/nishantkalane/sentiment-sense",
        demo: "https://sentiment-sense.vercel.app",
      },
    ],
    experience: [
      {
        title: "Cybersecurity Intern",
        company: "CISCO/NIIT Foundation",
        location: "Remote",
        period: "Jun 2025",
        description: "Worked on cybersecurity projects focusing on network security and threat analysis.",
        responsibilities: [
          "Analyzed network security vulnerabilities",
          "Implemented security protocols and best practices",
          "Conducted threat assessment and risk analysis",
          "Collaborated with team on security solutions",
        ],
      },
      {
        title: "Graduate Research Assistant",
        company: "Govt. College of Engineering",
        location: "Nagpur",
        period: "Aug 2023 – Jan 2024",
        description: "Conducted research in AI/ML applications with focus on NLP and healthcare robotics.",
        responsibilities: [
          "Led research projects in NLP and machine learning",
          "Mentored undergraduate students in robotics projects",
          "Published research papers in national conferences",
          "Collaborated with faculty on interdisciplinary research",
        ],
      },
      {
        title: "Finance Intern",
        company: "J.P.A Associates",
        location: "Nagpur",
        period: "Mar 2024 – Apr 2024",
        description: "Gained experience in financial analysis and business operations.",
        responsibilities: [
          "Assisted in financial data analysis and reporting",
          "Supported client relationship management",
          "Participated in business process optimization",
          "Learned financial modeling and forecasting techniques",
        ],
      },
    ],
    education: [
      {
        degree: "B.Tech in Computer Science & Engineering",
        institution: "Govt. College of Engineering",
        location: "Nagpur",
        period: "2022 – Present",
        description: "Specializing in AI/ML with focus on NLP, robotics, and healthcare applications.",
      },
      {
        degree: "Higher Secondary Education",
        institution: "Fergusson College",
        location: "Pune",
        period: "2019 – 2022",
        description: "Completed with distinction in Science stream.",
      },
      {
        degree: "Secondary Education",
        institution: "St. Thomas Public School",
        location: "Pune",
        period: "2014 – 2019",
        description: "Strong foundation in mathematics and sciences.",
      },
      {
        degree: "Primary Education",
        institution: "Mary Memorial High School",
        location: "Ahmednagar",
        period: "2007 – 2014",
        description: "Early education with focus on holistic development.",
      },
    ],
    skills: {
      technical: ["Python", "SQL", "LLMs", "Power BI"],
      interpersonal: ["Communication", "Leadership"],
      analytical: ["Critical Thinking", "Research"],
      support: ["Research Assistance"],
    },
    awards: [
      {
        place: "🥇 1st Prize",
        event: "Techno Docx, Esperanza 2k24",
        type: "Research Paper Presentation",
        college: "Prof. Ram Meghe Institute, Badnera-Amravati",
        date: "31/01/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "🥇 1st Prize",
        event: "TechKnowledge",
        type: "Research Paper Presentation",
        college: "Swaminarayan Siddhanta Institute, Nagpur",
        date: "12/03/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "❌ Participated",
        event: "Paper Presentation",
        type: "Paper Presentation",
        college: "G.H. Raisoni College, Nagpur",
        date: "15/04/2024",
        mode: "Offline",
        level: "College Level",
      },
      {
        place: "🥈 2nd Prize",
        event: "Tech Symposium, SHIKAR-2024",
        type: "Technical Presentation",
        college: "Jhulelal Institute of Technology",
        date: "16/03/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "🥇 1st Prize",
        event: "PaperIx-2024",
        type: "Paper Presentation",
        college: "St. Mother Theresa Engineering College, Tamilnadu",
        date: "28/09/2024",
        mode: "Online",
        level: "National Level",
      },
      {
        place: "🥇 1st Prize",
        event: "IEEE Paper Presentation",
        type: "Paper Presentation",
        college: "Study World College of Engineering, Coimbatore",
        date: "03/10/2024",
        mode: "Online",
        level: "National Level",
      },
      {
        place: "❌ Participated",
        event: "Paper Presentation",
        type: "Paper Presentation",
        college: "Study World College, Coimbatore",
        date: "15/10/2024",
        mode: "Online",
        level: "National Level",
      },
      {
        place: "🥇 1st Prize",
        event: "Amphiroz-2k24",
        type: "Paper Presentation",
        college: "AAA College, Virudhunagar",
        date: "16/10/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "🥇 1st Prize",
        event: "Amphiroz-2k24 (Twisted Tiles)",
        type: "Best Technical Answers",
        college: "AAA College, Virudhunagar",
        date: "16/10/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "🥉 3rd Prize",
        event: "Amphiroz-2k24",
        type: "Project Presentation",
        college: "AAA College, Virudhunagar",
        date: "16/10/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "⭐ Overall Star Performer",
        event: "Amphiroz-2k24",
        type: "Multi-Event Competition",
        college: "AAA College, Virudhunagar",
        date: "16/10/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "❌ Participated",
        event: "Paper Presentation",
        type: "Paper Presentation",
        college: "Sri Krishna College, Coimbatore",
        date: "17/10/2025",
        mode: "Online",
        level: "National Level",
      },
      {
        place: "🥇 1st Prize",
        event: "TechnoKings2k24",
        type: "Paper Presentation",
        college: "Kings Engineering College, Chennai",
        date: "18/10/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "🥇 1st Prize",
        event: "NetCOM 2k24",
        type: "Paper Presentation",
        college: "JJ College, Tiruchirappalli",
        date: "19/10/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "🥇 1st Prize",
        event: "Xenix-24",
        type: "Paper Presentation",
        college: "Mahendra College, Salem",
        date: "22/10/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "🥇 1st Prize",
        event: "Spectra'24",
        type: "Enchanted Paper",
        college: "Kongu College, Erode",
        date: "23/10/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "🥈 2nd Prize",
        event: "CebRoid'24",
        type: "Citadel Chronicles",
        college: "Adhi College, Kanchipuram",
        date: "24/10/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "🥇 1st Prize",
        event: "Festronix'2k24",
        type: "Paper Presentation",
        college: "K.Ramakrishnan College, Tiruchirappalli",
        date: "25/10/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "🥇 1st Prize",
        event: "Festronix'2k24",
        type: "Ideathon",
        college: "K.Ramakrishnan College, Tiruchirappalli",
        date: "25/10/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "🥇 1st Prize",
        event: "Kratos'24",
        type: "Paper Presentation",
        college: "SRM Easwari Engineering College, Chennai",
        date: "26/10/2024",
        mode: "Offline",
        level: "National Level",
      },
      {
        place: "❌ Participated",
        event: "ICPER'25",
        type: "Poster Presentation",
        college: "Government College of Engineering, Nagpur",
        date: "21/01/2025",
        mode: "Offline",
        level: "National Level",
      },
    ],
    blogs: [
      {
        title: "Engineering Students Built a Project 'EmployNet' to Break the Paradox of Employment",
        description:
          "A comprehensive look at how engineering students are tackling employment challenges through innovative technology solutions.",
        url: "https://medium.com/@nishhhh_ant/engineering-students-built-a-project-employnet-to-break-the-paradox-of-employment-ac5ab32f9a37",
        date: "2024",
        platform: "Medium",
        readTime: "5 min read",
        tags: ["Employment", "Technology", "Innovation", "Engineering"],
      },
    ],
  }
}
